#服务端口
server:
  port: 8001
#服务名
spring:
  application:
    name: service-edu
    #环境设置：dev  test  prod
  profiles:
    active: dev

  #数据库链接设置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:jdbc: mysql://localhost:3306/guli?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 19990217
#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
